"""
TrustGate doc generator — scans the codebase and writes docs/ from source truth.
Run:  python .cursor/skills/doc-sync/scripts/generate_docs.py
"""

from __future__ import annotations

import ast
import json
import os
import re
import textwrap
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]  # TrustGate/
BACKEND = ROOT / "backend"
FRONTEND = ROOT / "frontend"
DOCS = ROOT / "docs"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace") if path.exists() else ""


def _parse_ast(path: Path) -> ast.Module | None:
    src = _read(path)
    if not src:
        return None
    try:
        return ast.parse(src)
    except SyntaxError:
        return None


def _stamp() -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return (
        f"> Auto-generated by `doc-sync` on {ts}.\n"
        f"> Do not edit — re-run `python .cursor/skills/doc-sync/scripts/generate_docs.py`.\n"
    )


# ---------------------------------------------------------------------------
# 1. API Reference
# ---------------------------------------------------------------------------

_HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}


def _extract_routes(api_dir: Path) -> list[dict]:
    routes: list[dict] = []
    for py in sorted(api_dir.glob("*.py")):
        if py.name.startswith("_"):
            continue
        tree = _parse_ast(py)
        if not tree:
            continue
        tag = py.stem
        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            for deco in node.decorator_list:
                method = path_str = ""
                response_model = ""
                status_code = ""
                if isinstance(deco, ast.Attribute) and deco.attr in _HTTP_METHODS:
                    method = deco.attr.upper()
                elif isinstance(deco, ast.Call):
                    func = deco.func
                    if isinstance(func, ast.Attribute) and func.attr in _HTTP_METHODS:
                        method = func.attr.upper()
                        for arg in deco.args:
                            if isinstance(arg, ast.Constant):
                                path_str = arg.value
                        for kw in deco.keywords:
                            if kw.arg == "response_model":
                                response_model = ast.unparse(kw.value)
                            if kw.arg == "status_code":
                                status_code = ast.unparse(kw.value)
                if not method:
                    continue

                params = []
                for a in node.args.args:
                    if a.arg in ("self", "db", "background_tasks"):
                        continue
                    ann = ast.unparse(a.annotation) if a.annotation else ""
                    params.append(f"{a.arg}: {ann}" if ann else a.arg)

                routes.append({
                    "tag": tag,
                    "method": method,
                    "path": path_str or "/",
                    "name": node.name,
                    "params": params,
                    "response_model": response_model,
                    "status_code": status_code,
                    "line": node.lineno,
                    "file": py.name,
                })
    return routes


def _prefix_for_tag(tag: str) -> str:
    mapping = {
        "projects": "/api/v1/projects",
        "targets": "/api/v1/targets",
        "scans": "/api/v1/scans",
        "findings": "/api/v1/findings",
    }
    return mapping.get(tag, f"/api/v1/{tag}")


def generate_api_reference() -> str:
    lines = [f"# API Reference\n\n{_stamp()}\n"]
    lines.append("Base URL: `https://trustgate-api-prod.fly.dev` (production) "
                  "| `http://localhost:8000` (local)\n\n")
    lines.append("## Health Check\n\n| Method | Path | Response |\n|---|---|---|\n"
                 "| GET | `/health` | `{\"status\":\"ok\",\"version\":\"0.1.0\"}` |\n\n")

    api_dir = BACKEND / "app" / "api"
    routes = _extract_routes(api_dir)
    if not routes:
        lines.append("_No routes detected._\n")
        return "\n".join(lines)

    tags = sorted({r["tag"] for r in routes})
    for tag in tags:
        prefix = _prefix_for_tag(tag)
        lines.append(f"## {tag.title()}\n")
        lines.append("| Method | Endpoint | Handler | Response Model | Status |\n")
        lines.append("|--------|----------|---------|----------------|--------|\n")
        for r in routes:
            if r["tag"] != tag:
                continue
            full = f"`{prefix}{r['path']}`"
            rm = f"`{r['response_model']}`" if r["response_model"] else "—"
            sc = r["status_code"] or "200"
            lines.append(f"| {r['method']} | {full} | `{r['name']}` | {rm} | {sc} |\n")
        lines.append("\n")

        for r in routes:
            if r["tag"] != tag:
                continue
            if r["params"]:
                lines.append(f"### `{r['method']} {prefix}{r['path']}`\n\n")
                lines.append("**Parameters:**\n\n")
                for p in r["params"]:
                    lines.append(f"- `{p}`\n")
                lines.append("\n")

    return "".join(lines)


# ---------------------------------------------------------------------------
# 2. Data Models
# ---------------------------------------------------------------------------

def _extract_columns(models_dir: Path) -> dict[str, list[dict]]:
    result: dict[str, list[dict]] = {}
    for py in sorted(models_dir.glob("*.py")):
        if py.name.startswith("_"):
            continue
        tree = _parse_ast(py)
        if not tree:
            continue
        for node in ast.walk(tree):
            if not isinstance(node, ast.ClassDef):
                continue
            bases = [ast.unparse(b) for b in node.bases]
            if not any("Base" in b for b in bases):
                continue
            cols = []
            tablename = ""
            for item in node.body:
                if isinstance(item, ast.Assign):
                    for t in item.targets:
                        if isinstance(t, ast.Name) and t.id == "__tablename__":
                            tablename = ast.unparse(item.value).strip("'\"")
                if isinstance(item, ast.AnnAssign) and item.target:
                    name = ast.unparse(item.target)
                    ann = ast.unparse(item.annotation) if item.annotation else ""
                    cols.append({"name": name, "type": ann})
            result[node.name] = cols
            if tablename:
                result[node.name].insert(0, {"name": "__tablename__", "type": tablename})
    return result


def _extract_schemas(schemas_dir: Path) -> dict[str, list[dict]]:
    result: dict[str, list[dict]] = {}
    for py in sorted(schemas_dir.glob("*.py")):
        if py.name.startswith("_"):
            continue
        tree = _parse_ast(py)
        if not tree:
            continue
        for node in ast.walk(tree):
            if not isinstance(node, ast.ClassDef):
                continue
            fields = []
            for item in node.body:
                if isinstance(item, ast.AnnAssign) and item.target:
                    name = ast.unparse(item.target)
                    ann = ast.unparse(item.annotation) if item.annotation else ""
                    default = ""
                    if item.value:
                        default = ast.unparse(item.value)
                    fields.append({"name": name, "type": ann, "default": default})
            if fields:
                result[node.name] = fields
    return result


def generate_data_models() -> str:
    lines = [f"# Data Models\n\n{_stamp()}\n"]

    models = _extract_columns(BACKEND / "app" / "models")
    schemas = _extract_schemas(BACKEND / "app" / "schemas")

    lines.append("## ORM Models (SQLAlchemy)\n\n")
    for cls, cols in models.items():
        table = ""
        display_cols = []
        for c in cols:
            if c["name"] == "__tablename__":
                table = c["type"]
            else:
                display_cols.append(c)
        header = f"### `{cls}`" + (f" — table `{table}`" if table else "")
        lines.append(f"{header}\n\n")
        lines.append("| Column | Type |\n|--------|------|\n")
        for c in display_cols:
            lines.append(f"| `{c['name']}` | `{c['type']}` |\n")
        lines.append("\n")

    lines.append("## Pydantic Schemas\n\n")
    for cls, fields in schemas.items():
        lines.append(f"### `{cls}`\n\n")
        lines.append("| Field | Type | Default |\n|-------|------|---------|\n")
        for f in fields:
            d = f"`{f['default']}`" if f["default"] else "—"
            lines.append(f"| `{f['name']}` | `{f['type']}` | {d} |\n")
        lines.append("\n")

    return "".join(lines)


# ---------------------------------------------------------------------------
# 3. Architecture
# ---------------------------------------------------------------------------

def generate_architecture() -> str:
    lines = [f"# Architecture\n\n{_stamp()}\n"]

    lines.append("## System Overview\n\n")
    lines.append("```\n")
    lines.append("┌─────────────────┐     ┌─────────────────┐     ┌──────────────┐\n")
    lines.append("│  Next.js 15     │────▶│  FastAPI         │────▶│  Neon        │\n")
    lines.append("│  (Vercel)       │     │  (Fly.io)        │     │  PostgreSQL  │\n")
    lines.append("└─────────────────┘     └────────┬─────────┘     └──────────────┘\n")
    lines.append("                                 │\n")
    lines.append("                        ┌────────▼─────────┐\n")
    lines.append("                        │  Upstash Redis   │\n")
    lines.append("                        │  (Fly.io)        │\n")
    lines.append("                        └──────────────────┘\n")
    lines.append("```\n\n")

    lines.append("## Directory Structure\n\n```\n")
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in {
            "node_modules", ".next", "__pycache__", ".git", ".venv",
            "venv", ".cursor", ".vercel", "dist",
        }]
        rel = os.path.relpath(dirpath, ROOT)
        depth = rel.count(os.sep) if rel != "." else 0
        indent = "  " * depth
        folder = os.path.basename(dirpath) if rel != "." else "TrustGate/"
        lines.append(f"{indent}{folder}/\n")
        for f in sorted(filenames):
            if f.startswith(".") and f not in {".env.example", ".dockerignore", ".gitignore"}:
                continue
            lines.append(f"{indent}  {f}\n")
    lines.append("```\n\n")

    lines.append("## Data Flow\n\n")
    lines.append("1. User triggers scan via Dashboard or API\n")
    lines.append("2. Backend creates `Scan` record (status=pending)\n")
    lines.append("3. Background task runs garak against the `Target` model\n")
    lines.append("4. Results are normalized into `Finding` records with OWASP mapping\n")
    lines.append("5. Safety score is computed and `Scan` record updated\n")
    lines.append("6. Dashboard polls for results and renders charts\n\n")

    lines.append("## Tech Stack\n\n")
    lines.append("| Layer | Technology | Deployed To |\n")
    lines.append("|-------|-----------|-------------|\n")

    pkg_json = FRONTEND / "package.json"
    fe_deps = ""
    if pkg_json.exists():
        pj = json.loads(_read(pkg_json))
        fe_deps = ", ".join(sorted(pj.get("dependencies", {}).keys()))

    pyproject = BACKEND / "pyproject.toml"
    be_deps = ""
    if pyproject.exists():
        content = _read(pyproject)
        m = re.findall(r'"([a-zA-Z][a-zA-Z0-9_-]*)', content)
        be_deps = ", ".join(sorted(set(m)))

    lines.append(f"| Frontend | Next.js, React, Tailwind, shadcn/ui | Vercel |\n")
    lines.append(f"| Backend  | FastAPI, SQLAlchemy, Pydantic, uvicorn | Fly.io |\n")
    lines.append(f"| Database | PostgreSQL (Neon serverless) | Neon |\n")
    lines.append(f"| Cache    | Redis (Upstash) | Fly.io |\n")
    lines.append(f"| Scanner  | garak v0.14+ | Local / CI |\n")
    lines.append(f"| CI/CD    | GitHub Actions | GitHub |\n\n")

    return "".join(lines)


# ---------------------------------------------------------------------------
# 4. Environment Variables
# ---------------------------------------------------------------------------

def generate_environment() -> str:
    lines = [f"# Environment Variables\n\n{_stamp()}\n"]

    config_path = BACKEND / "app" / "config.py"
    tree = _parse_ast(config_path)
    if tree:
        lines.append("## Backend (`backend/app/config.py` → `Settings`)\n\n")
        lines.append("| Variable | Type | Default | Purpose |\n")
        lines.append("|----------|------|---------|---------|\n")

        for node in ast.walk(tree):
            if not isinstance(node, ast.ClassDef) or node.name != "Settings":
                continue
            for item in node.body:
                if not isinstance(item, ast.AnnAssign) or not item.target:
                    continue
                name = ast.unparse(item.target)
                ann = ast.unparse(item.annotation) if item.annotation else ""
                default = ast.unparse(item.value) if item.value else "—"
                env_name = name.upper()
                purpose = _env_purpose(name)
                lines.append(f"| `{env_name}` | `{ann}` | `{default}` | {purpose} |\n")
        lines.append("\n")

    lines.append("## Frontend\n\n")
    lines.append("| Variable | Default | Purpose |\n")
    lines.append("|----------|---------|---------|\n")
    lines.append("| `NEXT_PUBLIC_API_URL` | `http://localhost:8000` | Backend API base URL |\n\n")

    lines.append("## CI/CD Secrets (GitHub Actions)\n\n")
    lines.append("| Secret | Used By |\n|--------|---------|\n")
    lines.append("| `FLY_API_TOKEN` | `deploy.yml` — Fly.io backend deploy |\n")
    lines.append("| `VERCEL_TOKEN` | `deploy.yml` — Vercel frontend deploy |\n")
    lines.append("| `VERCEL_ORG_ID` | `deploy.yml` — Vercel org scope |\n")
    lines.append("| `VERCEL_PROJECT_ID` | `deploy.yml` — Vercel project |\n\n")

    env_example = ROOT / ".env.example"
    if env_example.exists():
        lines.append("## `.env.example`\n\n```env\n")
        lines.append(_read(env_example))
        lines.append("```\n")

    return "".join(lines)


def _env_purpose(name: str) -> str:
    purposes = {
        "app_name": "Application display name",
        "api_secret_key": "Secret for JWT / session signing",
        "debug": "Enable debug mode",
        "database_url": "PostgreSQL connection string (asyncpg)",
        "redis_url": "Redis connection string",
        "cors_origins": "Comma-separated allowed CORS origins",
        "openai_api_key": "OpenAI API key for scanner targets",
        "anthropic_api_key": "Anthropic API key for scanner targets",
        "azure_openai_api_key": "Azure OpenAI key",
        "azure_openai_endpoint": "Azure OpenAI endpoint URL",
        "hf_token": "Hugging Face token",
    }
    return purposes.get(name, "—")


# ---------------------------------------------------------------------------
# 5. Deployment Guide
# ---------------------------------------------------------------------------

def generate_deployment() -> str:
    lines = [f"# Deployment Guide\n\n{_stamp()}\n"]

    lines.append("## Production URLs\n\n")
    lines.append("| Service | URL |\n|---------|-----|\n")
    lines.append("| Backend API | https://trustgate-api-prod.fly.dev |\n")
    lines.append("| Frontend    | https://trustgate-dashboard.vercel.app |\n")
    lines.append("| Database    | Neon Postgres (us-east-1) |\n\n")

    fly_toml = BACKEND / "fly.toml"
    if fly_toml.exists():
        lines.append("## Backend — Fly.io\n\n")
        lines.append("```toml\n")
        lines.append(_read(fly_toml))
        lines.append("```\n\n")
        lines.append("**Deploy:** `fly deploy` from `backend/`\n\n")
        lines.append("**Set secrets:**\n```bash\n")
        lines.append("fly secrets set DATABASE_URL='...' REDIS_URL='...' CORS_ORIGINS='...'\n")
        lines.append("```\n\n")

    vercel_json = FRONTEND / "vercel.json"
    if vercel_json.exists():
        lines.append("## Frontend — Vercel\n\n")
        lines.append("```json\n")
        lines.append(_read(vercel_json))
        lines.append("```\n\n")
        lines.append("**Deploy:** `npx vercel --prod` from `frontend/`\n\n")

    lines.append("## Database — Neon\n\n")
    lines.append("- Serverless PostgreSQL on `us-east-1`\n")
    lines.append("- Connection via `DATABASE_URL` with SSL (auto-detected for `neon.tech` hosts)\n")
    lines.append("- Tables auto-created on backend startup via SQLAlchemy `create_all`\n\n")

    lines.append("## CI/CD — GitHub Actions\n\n")
    ci = ROOT / ".github" / "workflows" / "ci.yml"
    deploy = ROOT / ".github" / "workflows" / "deploy.yml"
    if ci.exists():
        lines.append(f"- **CI** (`ci.yml`): Runs on push/PR to main. Lints (ruff), tests (pytest), builds frontend.\n")
    if deploy.exists():
        lines.append(f"- **Deploy** (`deploy.yml`): Runs on push to main. Auto-deploys backend to Fly.io, frontend to Vercel.\n")
    lines.append("\n")

    lines.append("## Docker (Local)\n\n```bash\ndocker-compose up --build\n```\n\n")
    lines.append("Services: backend (:8000), frontend (:3000), postgres (:5432), redis (:6379)\n")

    return "".join(lines)


# ---------------------------------------------------------------------------
# 6. Development Guide
# ---------------------------------------------------------------------------

def generate_development() -> str:
    lines = [f"# Development Guide\n\n{_stamp()}\n"]

    lines.append("## Prerequisites\n\n")
    lines.append("- Python 3.12+\n- Node.js 18+\n- Docker & Docker Compose\n- `uv` (Python package manager)\n\n")

    lines.append("## Local Setup\n\n")
    lines.append("```bash\n")
    lines.append("# Clone\ngit clone https://github.com/gengirish/trustgate.git\ncd trustgate\ncp .env.example .env\n\n")
    lines.append("# Backend\ncd backend\nuv sync\nuv run uvicorn app.main:app --reload\n\n")
    lines.append("# Frontend (separate terminal)\ncd frontend\nnpm install\nnpm run dev\n\n")
    lines.append("# Or use Docker\ndocker-compose up --build\n```\n\n")

    lines.append("## Testing\n\n```bash\ncd backend\nuv run pytest          # run all tests\nuv run pytest -v      # verbose\n```\n\n")

    lines.append("## Linting\n\n```bash\ncd backend\nuv run ruff check .    # check\nuv run ruff check . --fix  # auto-fix\n```\n\n")

    lines.append("## Scripts\n\n")
    scripts_dir = ROOT / "scripts"
    if scripts_dir.exists():
        lines.append("| Script | Purpose |\n|--------|---------|\n")
        for py in sorted(scripts_dir.glob("*.py")):
            doc = ""
            tree = _parse_ast(py)
            if tree and ast.get_docstring(tree):
                doc = ast.get_docstring(tree).split("\n")[0]
            lines.append(f"| `scripts/{py.name}` | {doc or py.stem} |\n")
        lines.append("\n")

    lines.append("## Project Conventions\n\n")
    lines.append("- Backend uses `uv` (not pip) — `pyproject.toml` + `uv.lock`\n")
    lines.append("- All API routes are under `/api/v1/`\n")
    lines.append("- ORM models in `backend/app/models/`, Pydantic schemas in `backend/app/schemas/`\n")
    lines.append("- Frontend uses App Router (Next.js 15)\n")
    lines.append("- Tailwind CSS 4 + shadcn/ui for styling\n")

    return "".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    DOCS.mkdir(exist_ok=True)

    generators = {
        "API_REFERENCE.md": generate_api_reference,
        "DATA_MODELS.md": generate_data_models,
        "ARCHITECTURE.md": generate_architecture,
        "ENVIRONMENT.md": generate_environment,
        "DEPLOYMENT.md": generate_deployment,
        "DEVELOPMENT.md": generate_development,
    }

    for filename, gen_fn in generators.items():
        path = DOCS / filename
        content = gen_fn()
        path.write_text(content, encoding="utf-8")
        print(f"  wrote {path.relative_to(ROOT)}")

    print(f"\nDocs generated: {len(generators)} files in docs/")


if __name__ == "__main__":
    main()
